### ISSUE TITLE
Link to Custom Bots is broken in README.md

### ISSUE THREAD

**Issue by GregHarriett** [zegervdv/hubot-ms-teams#2]
Noticed that the "Custom Bot" link was no longer valid.  I did a little looking around and found a number of alternatives.  The best looks to be this - https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-conversations#replying-to-messages

Fixed it in the file but found I could not do a pull request to your repo.  

BTW, thank you for trying to put something together on Hubot in MS Teams.  My group is looking to do this and may move forward with what you have here as a guidepost.

**Comment by zegervdv** [comment]
Weird the pull request doesn’t work. What’s the issue you’re seeing?

Sadly, due to our closed network I can’t get the other way to work. 
I’m hoping the the “on premise” bot system will be implemented soon. 

Anyway, if you have any progress feel free to do a pull request (if it works)

**Comment by GregHarriett** [comment]
On the pull request this is the message I get back.
![image](https://user-images.githubusercontent.com/13560335/36503011-b257890c-1719-11e8-98b5-3c21c1d1cb9d.png)

**Comment by zegervdv** [comment]
Did you do a fork of the github page? You can’t push directly to my repo. You need to make your own fork, push your changes to it and then raise the pull request from there.

**Comment by GregHarriett** [comment]
No I just did a clone.  I'll try forking it.

**Comment by GregHarriett** [comment]
Ok, looks like forking it did the trick.  If it's open source I would not think that forking to my user would be needed.  Not sure I understand why using a clone doesn't allow the pull request.  Likely my ignorance.

**Comment by zegervdv** [comment]
It’s to give the owner some control over what gets added I guess. 
You can find some more info in the github help pages: https://help.github.com/articles/about-pull-requests/

Anyway thanks for your fix!
